[3.x] Avoid double worker connection (#31)
The ping took some time during worker arbitration procedure,
and the new connection might have already been dropped.
Drop the first connection to avoid duplication.

Fixes the issue https://github.com/buildbot/buildbot/issues/4678

The fresh logs are:
```
2026-09-08 21:15:59+0000 [Broker,3535,50.117.36.30] worker 'doug-worker-1b' attaching from IPv4Address(type='TCP', host='50.117.36.30', port=21167)
2026-09-08 21:15:59+0000 [Broker,3535,50.117.36.30] Got duplication connection from 'doug-worker-1b' starting arbitration procedure
2026-09-08 21:15:59+0000 [Broker,3535,50.117.36.30] Got error while trying to ping connected worker doug-worker-1b:Calling Stale Broker
2026-09-08 21:15:59+0000 [Broker,3535,50.117.36.30] Old connection for 'doug-worker-1b' was lost, accepting new
2026-09-08 21:16:00+0000 [Broker,3535,50.117.36.30] Got workerinfo from 'doug-worker-1b'
2026-09-08 21:16:00+0000 [Broker,3535,50.117.36.30] worker doug-worker-1b cannot attach
	Traceback (most recent call last):
	  File "/home/llvm-buildbot/buildbot/master/buildbot/worker/base.py", line 755, in attached
	    log.err(e, f"worker {self.name} cannot attach")
	--- <exception caught here> ---
	  File "/home/llvm-buildbot/buildbot/master/buildbot/worker/base.py", line 753, in attached
	    yield super().attached(conn)
	builtins.AssertionError: doug-worker-1b: 50.117.36.30:21167 connecting, but we are already connected to: 104.165.194.1:16133
```